apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-gateway
  namespace: llm
  annotations:
    konghq.com/plugins: "keyauth,ip-restriction,company-rate-limit"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/acme-challenge-type: "http01"
    konghq.com/protocols: "http,https"
spec:
  ingressClassName: kong
  rules:
  - host: {{ .Values.ingress.host | default "agent.reisdematos.ch" | quote }}
    http:
      paths:
      - path: /sanitize
        pathType: Prefix
        backend:
          service:
            name: guardrail
            port: 
              number: 80
      - path: /chat
        pathType: Prefix
        backend:
          service: 
            name: guardrail
            port: 
              number: 80
      - path: /healthz
        pathType: Prefix
        backend:
          service:
            name: guardrail
            port: 
              number: 80
  tls:
  - hosts:
      - {{ .Values.ingress.host | default "agent.reisdematos.ch" | quote }}
    secretName: {{ .Values.ingress.tls.secretName | default "llm-tls" | quote }}