---
# Grafana Configuration with Subpath Support
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: observability
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = 'agent.reisdematos.ch'
    root_url = 'https://agent.reisdematos.ch/grafana'
    serve_from_sub_path = true

---
# Grafana Service for Kong Ingress
apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: llm  # In Kong's namespace for easier ingress
spec:
  type: ExternalName
  externalName: grafana.observability.svc.cluster.local
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
