---
# Grafana Configuration with Subpath Support
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: observability
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = 'agent.reisdematos.ch'
    root_url = 'https://agent.reisdematos.ch/grafana'
    serve_from_sub_path = true

---
# Grafana Service for Kong Ingress (Endpoint-based instead of ExternalName)
apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: llm  # In Kong's namespace for easier ingress
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000  # Forward to Grafana's actual port
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: grafana-external
  namespace: llm
subsets:
- addresses:
  - ip: 10.0.1.39  # IP of grafana pod
  ports:
  - port: 3000  # Grafana actual port
    protocol: TCP
