apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-unified-config
  namespace: observability
data:
  promtail.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 9096
      log_level: info

    clients:
      - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push

    positions:
      filename: /tmp/positions.yaml

    scrape_configs:
      # Simplified direct path matching for Kubernetes pod logs
      - job_name: kubernetes-pods-universal
        static_configs:
          - targets:
            - localhost
            labels:
              job: kubernetes-pods
              __path__: /var/log/pods/*/*/*.log
        pipeline_stages:
          # Parse CRI format logs first
          - cri: {}
          # Add labels from the file path
          - regex:
              expression: '/var/log/pods/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_[^/]+/(?P<container_name>[^/]+)/.*\.log'
              source: filename
          - labels:
              namespace:
              pod_name:
              container_name:
          # Only keep logs from our target namespaces  
          - match:
              selector: '{namespace=~"llm|observability|default|kube-system"}'
              stages:
                # Try to parse as JSON if possible (for structured logs like LLM metrics)
                - json:
                    expressions:
                      timestamp: asctime
                      logger_name: name
                      level: levelname
                      message: message
                      # LLM-specific fields (will be ignored if not present)
                      request_id: request_id
                      model: model
                      input_tokens: input_tokens
                      output_tokens: output_tokens
                      total_tokens: total_tokens
                      processing_time: processing_time_seconds
                      energy_consumption: energy_consumption_kwh
                      cost: cost_usd
                      status: status
                    drop_malformed: false  # Don't drop non-JSON logs
                # Create labels from parsed fields
                - labels:
                    logger_name:
                    level:
                    model:
                    status:
                    request_id:
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-unified
  namespace: observability
spec:
  selector:
    matchLabels:
      name: promtail-unified
  template:
    metadata:
      labels:
        name: promtail-unified
    spec:
      serviceAccount: promtail
      containers:
        - name: promtail
          image: grafana/promtail:2.9.0
          args:
            - -config.file=/etc/promtail/promtail.yaml
          ports:
            - containerPort: 3101
              name: http-metrics
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      volumes:
        - name: config
          configMap:
            name: promtail-unified-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
