apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: keyauth
  namespace: llm
  annotations:
    kubernetes.io/ingress.class: kong
config:
  key_names:
  - X-API-Key
  - apikey
  run_on_preflight: false
plugin: key-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: reisdematos-team
  namespace: llm
  annotations:
    kubernetes.io/ingress.class: kong
username: reisdematos-team
---
apiVersion: v1
kind: Secret
metadata:
  name: reisdematos-api-key
  namespace: llm
  labels:
    konghq.com/credential: key-auth
stringData:
  key: "rdm-${RANDOM_KEY:-$(date +%s | sha256sum | head -c 32)}"
type: Opaque
---
# Additional consumer for frontend applications
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: frontend-app
  namespace: llm
  annotations:
    kubernetes.io/ingress.class: kong
username: frontend-app
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-api-key
  namespace: llm
  labels:
    konghq.com/credential: key-auth
stringData:
  key: "frontend-${RANDOM_KEY:-$(date +%s | sha256sum | head -c 32)}"
type: Opaque
