apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-auth
  namespace: llm
config:
  # Azure AD Configuration
  issuer: "https://login.microsoftonline.com/YOUR_TENANT_ID/v2.0"
  client_id: "YOUR_CLIENT_ID"
  client_secret: "YOUR_CLIENT_SECRET"
  redirect_uri: "https://agent.reisdematos.ch/auth/callback"
  scope: "openid email profile"
  response_type: "code"
  
  # Company domain restriction
  filters: |
    return function(claims)
      local email = claims.email or claims.preferred_username
      if not email or not string.match(email, "@reisdematos%.ch$") then
        kong.log.err("Access denied: email not from reisdematos.ch domain")
        return false, "Access denied: unauthorized domain"
      end
      return true
    end
    
  # Session configuration
  session_secret: "CHANGE_THIS_SECRET_KEY_32_CHARS_MIN"
  session_cookie_name: "rdm_session"
  session_cookie_secure: true
  session_cookie_httponly: true
  session_cookie_domain: ".reisdematos.ch"
  
plugin: oidc
---
# Rate limiting per user
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: user-rate-limit
  namespace: llm
config:
  minute: 100          # 100 requests per minute per user
  hour: 1000          # 1000 requests per hour per user
  policy: redis
  redis_host: redis-service.llm.svc.cluster.local
  redis_port: 6379
  identifier: consumer
plugin: rate-limiting-advanced
