apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-gateway
  namespace: llm          # same ns as the services
  annotations:
    konghq.com/plugins: keyauth,ratelimit  # (optional) cluster-wide plugins
    cert-manager.io/cluster-issuer: letsencrypt-staging
    konghq.com/protocols: "http,https"
spec:
  ingressClassName: kong
  rules:
  - host: llm.localtest.dev 
    http:
      paths:
      # hit guard-rail first – it decides whether to forward internally
      - path: /sanitize
        pathType: Prefix
        backend:
          service:
            name: guardrail
            port: 
              number: 8000
      - path: /chat
        pathType: Prefix
        backend:
          service: 
            name: guardrail
            port: 
              number: 8000
  tls:
  - hosts:
      - llm.localtest.dev # must resolve to your LoadBalancer IP
    secretName: llm-tls