#!/usr/bin/env bash
set -euo pipefail

echo "🎯 Opening your custom Grafana dashboards..."

echo ""
echo "✅ Your custom dashboards are now available!"
echo ""
echo "🔗 Direct Links:"
echo "1. MLOps Services Logs:"
echo "   http://localhost:3000/d/f6061184-be61-45ec-bf3f-b04fe0d8d37d/mlops-services-logs"
echo ""
echo "2. LLM Analytics & Metrics:"  
echo "   http://localhost:3000/d/eb9bb4e4-2c76-44ce-8a46-e0f5ea5e5b78/llm-analytics-metrics"
echo ""
echo "📊 Login Details:"
echo "   Username: admin"
echo "   Password: prom-operator"
echo ""
echo "🔍 What to expect:"
echo ""
echo "📋 MLOps Services Logs Dashboard:"
echo "   - Live logs from Guardrail service"
echo "   - Live logs from LLM-Proxy service"
echo "   - Live logs from Kong Gateway"
echo "   - Filtered error logs"
echo ""
echo "🧠 LLM Analytics & Metrics Dashboard:"
echo "   - LLM request rate statistics"
echo "   - Token usage tracking"
echo "   - Energy consumption estimates"
echo "   - Cost analysis"
echo "   - Live LLM request logs"
echo ""
echo "💡 Pro Tips:"
echo "   - Use the time picker to change the time range"
echo "   - Click on log lines to expand details"
echo "   - Use the search box to filter logs"
echo "   - The dashboards auto-refresh every 5 seconds"
echo ""
echo "🧪 To generate test data for LLM Analytics:"
echo "   ./scripts/test-llm-analytics.sh"
