name: build-and-deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_GUARDRAIL: ghcr.io/${{ github.repository_owner }}/guardrail:${{ github.sha }}
      IMAGE_PROXY:     ghcr.io/${{ github.repository_owner }}/llm-proxy:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Build & push Guardrail
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t $IMAGE_GUARDRAIL services/guardrail
          docker push $IMAGE_GUARDRAIL

      - name: Build & push LLM-proxy
        run: |
          docker build -t $IMAGE_PROXY services/llm-proxy
          docker push $IMAGE_PROXY

      # ----- deploy to AKS -----
      #- uses: azure/k8s-set-context@v3
      #  with:
      #    method: kubeconfig
      #    kubeconfig: ${{ secrets.KUBECONFIG_AKS_DEV }}

      #- uses: azure/setup-helm@v3

      #- name: Upgrade charts
      #  run: |
      #    helm upgrade --install guardrail charts/guardrail \
      #         --namespace llm --create-namespace \
      #         --set image.tag=${{ github.sha }}
      #    helm upgrade --install llm-proxy charts/llm-proxy \
      #         --namespace llm \
      #         --set image.tag=${{ github.sha }}